// This file has been generated by EWG. Do not edit. Changes will be lost!
// function glue code header
#include <my_winbase.h>

// Wraps call to function 'PtInRect' in a macro
#define ewg_function_macro_PtInRect(__ewg_macro_parameter_lprc, __ewg_macro_parameter_pt) PtInRect ((LPCRECT) __ewg_macro_parameter_lprc,  *((POINT*)__ewg_macro_parameter_pt))

// Wraps call to function 'WindowFromPoint' in a macro
#define ewg_function_macro_WindowFromPoint(__ewg_macro_parameter_Point) WindowFromPoint (*((POINT*)__ewg_macro_parameter_Point))

// Wraps call to function 'DragDetect' in a macro
#define ewg_function_macro_DragDetect(__ewg_macro_parameter_anonymous_1, __ewg_macro_parameter_anonymous_2) DragDetect ((HWND) __ewg_macro_parameter_anonymous_1, *((POINT*)__ewg_macro_parameter_anonymous_2))
