//typedef LRESULT (*wndproc_eiffel_feature) (void* a_class, HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4);

//wndproc
#include <windows.h>
#include <c/ewg_c_library/ewg_eiffel.h>
#include "callbacks.h"
#include "win32_callback_complement.h"

//wndproc
CALLBACK_ENTRIES_FORWARD(wndproc)
CALLBACK_DUMMY_RESULT_VALUE(wndproc,LRESULT)
CALLBACK_STUBS(wndproc,LRESULT,CALLBACK,WNDPROC_SIGNATURE,WNDPROC_PARAMETERS)
CALLBACK_ENTRIES(wndproc)
CALLBACK_NEW(wndproc)
CALLBACK_FREE(wndproc)
CALLBACK_GET_STUB(wndproc)
CALLBACK_CALL(wndproc,LRESULT,CALLBACK,WNDPROC_SIGNATURE,WNDPROC_PARAMETERS)

//dlgproc
CALLBACK_ENTRIES_FORWARD(dlgproc)
CALLBACK_DUMMY_RESULT_VALUE(dlgproc,LRESULT)
CALLBACK_STUBS(dlgproc,LRESULT,CALLBACK,DLGPROC_SIGNATURE,DLGPROC_PARAMETERS)
CALLBACK_ENTRIES(dlgproc)
CALLBACK_NEW(dlgproc)
CALLBACK_FREE(dlgproc)
CALLBACK_GET_STUB(dlgproc)
CALLBACK_CALL(dlgproc,LRESULT,CALLBACK,DLGPROC_SIGNATURE,DLGPROC_PARAMETERS)

//msgproc
CALLBACK_ENTRIES_FORWARD(msgproc)
CALLBACK_DUMMY_RESULT_VALUE(msgproc,LRESULT)
CALLBACK_STUBS(msgproc,LRESULT,CALLBACK,MSGPROC_SIGNATURE,MSGPROC_PARAMETERS)
CALLBACK_ENTRIES(msgproc)
CALLBACK_NEW(msgproc)
CALLBACK_FREE(msgproc)
CALLBACK_GET_STUB(msgproc)
CALLBACK_CALL(msgproc,LRESULT,CALLBACK,MSGPROC_SIGNATURE,MSGPROC_PARAMETERS)

//hookproc
CALLBACK_ENTRIES_FORWARD(hookproc)
CALLBACK_DUMMY_RESULT_VALUE(hookproc,LRESULT)
CALLBACK_STUBS(hookproc,LRESULT,CALLBACK,HOOKPROC_SIGNATURE,HOOKPROC_PARAMETERS)
CALLBACK_ENTRIES(hookproc)
CALLBACK_NEW(hookproc)
CALLBACK_FREE(hookproc)
CALLBACK_GET_STUB(hookproc)
CALLBACK_CALL(hookproc,LRESULT,CALLBACK,HOOKPROC_SIGNATURE,HOOKPROC_PARAMETERS)
