#ifndef __WIN32_CALLBACK_COMPLEMENT_H__
#define __WIN32_CALLBACK_COMPLEMENT_H__

#include "callbacks.h"

//wndproc
#define WNDPROC_SIGNATURE HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4
#define WNDPROC_PARAMETERS anonymous_1,anonymous_2,anonymous_3,anonymous_4


EIFFEL_CALLBACK_TYPEDEF(wndproc,LRESULT,WNDPROC_SIGNATURE)
CALLBACK_STRUCT(wndproc)
CALLBACK_PROTOTYPE_NEW(wndproc)
CALLBACK_PROTOTYPE_FREE(wndproc)
CALLBACK_PROTOTYPE_GET_STUB(wndproc)
CALLBACK_PROTOTYPE_CALL(wndproc,LRESULT,WNDPROC_SIGNATURE)

//dlgproc
#define DLGPROC_SIGNATURE HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4
#define DLGPROC_PARAMETERS anonymous_1,anonymous_2,anonymous_3,anonymous_4


EIFFEL_CALLBACK_TYPEDEF(dlgproc,LRESULT,DLGPROC_SIGNATURE)
CALLBACK_STRUCT(dlgproc)
CALLBACK_PROTOTYPE_NEW(dlgproc)
CALLBACK_PROTOTYPE_FREE(dlgproc)
CALLBACK_PROTOTYPE_GET_STUB(dlgproc)
CALLBACK_PROTOTYPE_CALL(dlgproc,LRESULT,DLGPROC_SIGNATURE)

//msgproc
#define MSGPROC_SIGNATURE HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4
#define MSGPROC_PARAMETERS anonymous_1,anonymous_2,anonymous_3,anonymous_4


EIFFEL_CALLBACK_TYPEDEF(msgproc,LRESULT,MSGPROC_SIGNATURE)
CALLBACK_STRUCT(msgproc)
CALLBACK_PROTOTYPE_NEW(msgproc)
CALLBACK_PROTOTYPE_FREE(msgproc)
CALLBACK_PROTOTYPE_GET_STUB(msgproc)
CALLBACK_PROTOTYPE_CALL(msgproc,LRESULT,MSGPROC_SIGNATURE)

//HOOK proc
//LRESULT CALLBACK HookProc(
//  int nCode,
//  WPARAM wParam,
//  LPARAM lParam
//);
//hookproc
#define HOOKPROC_SIGNATURE int nCode, WPARAM wParam, LPARAM lParam
#define HOOKPROC_PARAMETERS nCode, wParam, lParam

EIFFEL_CALLBACK_TYPEDEF(hookproc,LRESULT,HOOKPROC_SIGNATURE)
CALLBACK_STRUCT(hookproc)
CALLBACK_PROTOTYPE_NEW(hookproc)
CALLBACK_PROTOTYPE_FREE(hookproc)
CALLBACK_PROTOTYPE_GET_STUB(hookproc)
CALLBACK_PROTOTYPE_CALL(hookproc,LRESULT,HOOKPROC_SIGNATURE)


#endif

