-- This file has been generated by EWG. Do not edit. Changes will be lost!
class OSVERSIONINFOA_STRUCT

inherit

	EWG_STRUCT

	OSVERSIONINFOA_STRUCT_EXTERNAL
		export
			{NONE} all
		end

creation

	make_new_unshared,
	make_new_shared,
	make_unshared,
	make_shared

feature {NONE} -- Implementation

	sizeof: INTEGER is
		do
			Result := sizeof_external
		end

feature {ANY} -- Member Access

	get_dwosversioninfosize: INTEGER is
			-- Access member `dwOSVersionInfoSize'
		do
			Result := get_dwosversioninfosize_external (item)
		end

	set_dwosversioninfosize (a_value: INTEGER) is
			-- Set member `dwOSVersionInfoSize'
		do
			set_dwosversioninfosize_external (item, a_value)
		ensure
			a_value_set: a_value = get_dwosversioninfosize
		end

	get_dwmajorversion: INTEGER is
			-- Access member `dwMajorVersion'
		do
			Result := get_dwmajorversion_external (item)
		end

	set_dwmajorversion (a_value: INTEGER) is
			-- Set member `dwMajorVersion'
		do
			set_dwmajorversion_external (item, a_value)
		ensure
			a_value_set: a_value = get_dwmajorversion
		end

	get_dwminorversion: INTEGER is
			-- Access member `dwMinorVersion'
		do
			Result := get_dwminorversion_external (item)
		end

	set_dwminorversion (a_value: INTEGER) is
			-- Set member `dwMinorVersion'
		do
			set_dwminorversion_external (item, a_value)
		ensure
			a_value_set: a_value = get_dwminorversion
		end

	get_dwbuildnumber: INTEGER is
			-- Access member `dwBuildNumber'
		do
			Result := get_dwbuildnumber_external (item)
		end

	set_dwbuildnumber (a_value: INTEGER) is
			-- Set member `dwBuildNumber'
		do
			set_dwbuildnumber_external (item, a_value)
		ensure
			a_value_set: a_value = get_dwbuildnumber
		end

	get_dwplatformid: INTEGER is
			-- Access member `dwPlatformId'
		do
			Result := get_dwplatformid_external (item)
		end

	set_dwplatformid (a_value: INTEGER) is
			-- Set member `dwPlatformId'
		do
			set_dwplatformid_external (item, a_value)
		ensure
			a_value_set: a_value = get_dwplatformid
		end

end
