-- This file has been generated by EWG. Do not edit. Changes will be lost!
class RECOVERY_AGENT_INFORMATIONW_STRUCT

inherit

	EWG_STRUCT

	RECOVERY_AGENT_INFORMATIONW_STRUCT_EXTERNAL
		export
			{NONE} all
		end

creation

	make_new_unshared,
	make_new_shared,
	make_unshared,
	make_shared

feature {NONE} -- Implementation

	sizeof: INTEGER is
		do
			Result := sizeof_external
		end

feature {ANY} -- Member Access

	get_nextentryoffset: INTEGER is
			-- Access member `NextEntryOffset'
		do
			Result := get_nextentryoffset_external (item)
		end

	set_nextentryoffset (a_value: INTEGER) is
			-- Set member `NextEntryOffset'
		do
			set_nextentryoffset_external (item, a_value)
		ensure
			a_value_set: a_value = get_nextentryoffset
		end

	get_agentnamelength: INTEGER is
			-- Access member `AgentNameLength'
		do
			Result := get_agentnamelength_external (item)
		end

	set_agentnamelength (a_value: INTEGER) is
			-- Set member `AgentNameLength'
		do
			set_agentnamelength_external (item, a_value)
		ensure
			a_value_set: a_value = get_agentnamelength
		end

end
