-- This file has been generated by EWG. Do not edit. Changes will be lost!
class TAG_CURSORSHAPE_STRUCT

inherit

	EWG_STRUCT

	TAG_CURSORSHAPE_STRUCT_EXTERNAL
		export
			{NONE} all
		end

creation

	make_new_unshared,
	make_new_shared,
	make_unshared,
	make_shared

feature {NONE} -- Implementation

	sizeof: INTEGER is
		do
			Result := sizeof_external
		end

feature {ANY} -- Member Access

	get_xhotspot: INTEGER is
			-- Access member `xHotSpot'
		do
			Result := get_xhotspot_external (item)
		end

	set_xhotspot (a_value: INTEGER) is
			-- Set member `xHotSpot'
		do
			set_xhotspot_external (item, a_value)
		ensure
			a_value_set: a_value = get_xhotspot
		end

	get_yhotspot: INTEGER is
			-- Access member `yHotSpot'
		do
			Result := get_yhotspot_external (item)
		end

	set_yhotspot (a_value: INTEGER) is
			-- Set member `yHotSpot'
		do
			set_yhotspot_external (item, a_value)
		ensure
			a_value_set: a_value = get_yhotspot
		end

	get_cx: INTEGER is
			-- Access member `cx'
		do
			Result := get_cx_external (item)
		end

	set_cx (a_value: INTEGER) is
			-- Set member `cx'
		do
			set_cx_external (item, a_value)
		ensure
			a_value_set: a_value = get_cx
		end

	get_cy: INTEGER is
			-- Access member `cy'
		do
			Result := get_cy_external (item)
		end

	set_cy (a_value: INTEGER) is
			-- Set member `cy'
		do
			set_cy_external (item, a_value)
		ensure
			a_value_set: a_value = get_cy
		end

	get_cbwidth: INTEGER is
			-- Access member `cbWidth'
		do
			Result := get_cbwidth_external (item)
		end

	set_cbwidth (a_value: INTEGER) is
			-- Set member `cbWidth'
		do
			set_cbwidth_external (item, a_value)
		ensure
			a_value_set: a_value = get_cbwidth
		end

	get_planes: INTEGER is
			-- Access member `Planes'
		do
			Result := get_planes_external (item)
		end

	set_planes (a_value: INTEGER) is
			-- Set member `Planes'
		do
			set_planes_external (item, a_value)
		ensure
			a_value_set: a_value = get_planes
		end

	get_bitspixel: INTEGER is
			-- Access member `BitsPixel'
		do
			Result := get_bitspixel_external (item)
		end

	set_bitspixel (a_value: INTEGER) is
			-- Set member `BitsPixel'
		do
			set_bitspixel_external (item, a_value)
		ensure
			a_value_set: a_value = get_bitspixel
		end

end
