// This file has been generated by EWG. Do not edit. Changes will be lost!
// struct glue code header

#define ewg_struct_macro_struct_tagNONCLIENTMETRICSA_member_get_lfCaptionFont(a_item) &(((struct tagNONCLIENTMETRICSA * )a_item)->lfCaptionFont)

#define ewg_struct_macro_struct_tagNONCLIENTMETRICSA_member_get_lfSmCaptionFont(a_item) &(((struct tagNONCLIENTMETRICSA * )a_item)->lfSmCaptionFont)
#define ewg_struct_macro_struct_tagNONCLIENTMETRICSA_member_get_lfMenuFont(a_item) &(((struct tagNONCLIENTMETRICSA * )a_item)->lfMenuFont)
#define ewg_struct_macro_struct_tagNONCLIENTMETRICSA_member_get_lfStatusFont(a_item) &(((struct tagNONCLIENTMETRICSA * )a_item)->lfStatusFont)
#define ewg_struct_macro_struct_tagNONCLIENTMETRICSA_member_get_lfMessageFont(a_item) &(((struct tagNONCLIENTMETRICSA * )a_item)->lfMessageFont)
