// This file has been generated by EWG. Do not edit. Changes will be lost!
// callback glue code
#include <c\callback\ewg_callback_c_glue_code.h>
#include <c/ewg_c_library/ewg_eiffel.h>

struct pimage_tls_callback_entry_struct pimage_tls_callback_entry = {NULL, NULL};
void __stdcall pimage_tls_callback_stub (PVOID DllHandle, DWORD Reason, PVOID Reserved)
{
	if (pimage_tls_callback_entry.a_class != NULL && pimage_tls_callback_entry.feature != NULL)
	{
		pimage_tls_callback_entry.feature (eif_access(pimage_tls_callback_entry.a_class), DllHandle, Reason, Reserved);
	}
}
void set_pimage_tls_callback_entry (void* a_class, void* a_feature)
{
	pimage_tls_callback_entry.a_class = eif_adopt(a_class);
	pimage_tls_callback_entry.feature = (pimage_tls_callback_eiffel_feature) a_feature;
}
void* get_pimage_tls_callback_stub ()
{
	return (void*) pimage_tls_callback_stub;
}
void call_pimage_tls_callback (void* a_function, PVOID DllHandle, DWORD Reason, PVOID Reserved)
{
	((void(*)(PVOID DllHandle, DWORD Reason, PVOID Reserved))a_function)(DllHandle, Reason, Reserved);
}
struct pvoid_dword_pvoid_anonymous_callback_entry_struct pvoid_dword_pvoid_anonymous_callback_entry = {NULL, NULL};
void __stdcall pvoid_dword_pvoid_anonymous_callback_stub (PVOID DllHandle, DWORD Reason, PVOID Reserved)
{
	if (pvoid_dword_pvoid_anonymous_callback_entry.a_class != NULL && pvoid_dword_pvoid_anonymous_callback_entry.feature != NULL)
	{
		pvoid_dword_pvoid_anonymous_callback_entry.feature (eif_access(pvoid_dword_pvoid_anonymous_callback_entry.a_class), DllHandle, Reason, Reserved);
	}
}
void set_pvoid_dword_pvoid_anonymous_callback_entry (void* a_class, void* a_feature)
{
	pvoid_dword_pvoid_anonymous_callback_entry.a_class = eif_adopt(a_class);
	pvoid_dword_pvoid_anonymous_callback_entry.feature = (pvoid_dword_pvoid_anonymous_callback_eiffel_feature) a_feature;
}
void* get_pvoid_dword_pvoid_anonymous_callback_stub ()
{
	return (void*) pvoid_dword_pvoid_anonymous_callback_stub;
}
void call_pvoid_dword_pvoid_anonymous_callback (void* a_function, PVOID DllHandle, DWORD Reason, PVOID Reserved)
{
	((void(*)(PVOID DllHandle, DWORD Reason, PVOID Reserved))a_function)(DllHandle, Reason, Reserved);
}
struct waitortimercallbackfunc_entry_struct waitortimercallbackfunc_entry = {NULL, NULL};
void __stdcall waitortimercallbackfunc_stub (PVOID anonymous_1, BOOLEAN anonymous_2)
{
	if (waitortimercallbackfunc_entry.a_class != NULL && waitortimercallbackfunc_entry.feature != NULL)
	{
		waitortimercallbackfunc_entry.feature (eif_access(waitortimercallbackfunc_entry.a_class), anonymous_1, anonymous_2);
	}
}
void set_waitortimercallbackfunc_entry (void* a_class, void* a_feature)
{
	waitortimercallbackfunc_entry.a_class = eif_adopt(a_class);
	waitortimercallbackfunc_entry.feature = (waitortimercallbackfunc_eiffel_feature) a_feature;
}
void* get_waitortimercallbackfunc_stub ()
{
	return (void*) waitortimercallbackfunc_stub;
}
void call_waitortimercallbackfunc (void* a_function, PVOID anonymous_1, BOOLEAN anonymous_2)
{
	((void(*)(PVOID anonymous_1, BOOLEAN anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct workercallbackfunc_entry_struct workercallbackfunc_entry = {NULL, NULL};
void __stdcall workercallbackfunc_stub (PVOID anonymous_1)
{
	if (workercallbackfunc_entry.a_class != NULL && workercallbackfunc_entry.feature != NULL)
	{
		workercallbackfunc_entry.feature (eif_access(workercallbackfunc_entry.a_class), anonymous_1);
	}
}
void set_workercallbackfunc_entry (void* a_class, void* a_feature)
{
	workercallbackfunc_entry.a_class = eif_adopt(a_class);
	workercallbackfunc_entry.feature = (workercallbackfunc_eiffel_feature) a_feature;
}
void* get_workercallbackfunc_stub ()
{
	return (void*) workercallbackfunc_stub;
}
void call_workercallbackfunc (void* a_function, PVOID anonymous_1)
{
	((void(*)(PVOID anonymous_1))a_function)(anonymous_1);
}
struct farproc_entry_struct farproc_entry = {NULL, NULL};
int farproc_dummy_return_value;
int __stdcall farproc_stub (void)
{
	if (farproc_entry.a_class != NULL && farproc_entry.feature != NULL)
	{
		return farproc_entry.feature (eif_access(farproc_entry.a_class));
	}
	return farproc_dummy_return_value;
}
void set_farproc_entry (void* a_class, void* a_feature)
{
	farproc_entry.a_class = eif_adopt(a_class);
	farproc_entry.feature = (farproc_eiffel_feature) a_feature;
}
void* get_farproc_stub ()
{
	return (void*) farproc_stub;
}
int call_farproc (void* a_function)
{
	return ((int(*)(void))a_function)();
}
struct pthread_start_routine_entry_struct pthread_start_routine_entry = {NULL, NULL};
DWORD pthread_start_routine_dummy_return_value;
DWORD __stdcall pthread_start_routine_stub (LPVOID lpThreadParameter)
{
	if (pthread_start_routine_entry.a_class != NULL && pthread_start_routine_entry.feature != NULL)
	{
		return pthread_start_routine_entry.feature (eif_access(pthread_start_routine_entry.a_class), lpThreadParameter);
	}
	return pthread_start_routine_dummy_return_value;
}
void set_pthread_start_routine_entry (void* a_class, void* a_feature)
{
	pthread_start_routine_entry.a_class = eif_adopt(a_class);
	pthread_start_routine_entry.feature = (pthread_start_routine_eiffel_feature) a_feature;
}
void* get_pthread_start_routine_stub ()
{
	return (void*) pthread_start_routine_stub;
}
DWORD call_pthread_start_routine (void* a_function, LPVOID lpThreadParameter)
{
	return ((DWORD(*)(LPVOID lpThreadParameter))a_function)(lpThreadParameter);
}
struct ptop_level_exception_filter_entry_struct ptop_level_exception_filter_entry = {NULL, NULL};
LONG ptop_level_exception_filter_dummy_return_value;
LONG __stdcall ptop_level_exception_filter_stub (PEXCEPTION_POINTERS ExceptionInfo)
{
	if (ptop_level_exception_filter_entry.a_class != NULL && ptop_level_exception_filter_entry.feature != NULL)
	{
		return ptop_level_exception_filter_entry.feature (eif_access(ptop_level_exception_filter_entry.a_class), ExceptionInfo);
	}
	return ptop_level_exception_filter_dummy_return_value;
}
void set_ptop_level_exception_filter_entry (void* a_class, void* a_feature)
{
	ptop_level_exception_filter_entry.a_class = eif_adopt(a_class);
	ptop_level_exception_filter_entry.feature = (ptop_level_exception_filter_eiffel_feature) a_feature;
}
void* get_ptop_level_exception_filter_stub ()
{
	return (void*) ptop_level_exception_filter_stub;
}
LONG call_ptop_level_exception_filter (void* a_function, PEXCEPTION_POINTERS ExceptionInfo)
{
	return ((LONG(*)(PEXCEPTION_POINTERS ExceptionInfo))a_function)(ExceptionInfo);
}
struct pfe_export_func_entry_struct pfe_export_func_entry = {NULL, NULL};
DWORD pfe_export_func_dummy_return_value;
DWORD  pfe_export_func_stub (PBYTE pbData, PVOID pvCallbackContext, ULONG ulLength)
{
	if (pfe_export_func_entry.a_class != NULL && pfe_export_func_entry.feature != NULL)
	{
		return pfe_export_func_entry.feature (eif_access(pfe_export_func_entry.a_class), pbData, pvCallbackContext, ulLength);
	}
	return pfe_export_func_dummy_return_value;
}
void set_pfe_export_func_entry (void* a_class, void* a_feature)
{
	pfe_export_func_entry.a_class = eif_adopt(a_class);
	pfe_export_func_entry.feature = (pfe_export_func_eiffel_feature) a_feature;
}
void* get_pfe_export_func_stub ()
{
	return (void*) pfe_export_func_stub;
}
DWORD call_pfe_export_func (void* a_function, PBYTE pbData, PVOID pvCallbackContext, ULONG ulLength)
{
	return ((DWORD(*)(PBYTE pbData, PVOID pvCallbackContext, ULONG ulLength))a_function)(pbData, pvCallbackContext, ulLength);
}
struct pfe_import_func_entry_struct pfe_import_func_entry = {NULL, NULL};
DWORD pfe_import_func_dummy_return_value;
DWORD  pfe_import_func_stub (PBYTE pbData, PVOID pvCallbackContext, PULONG ulLength)
{
	if (pfe_import_func_entry.a_class != NULL && pfe_import_func_entry.feature != NULL)
	{
		return pfe_import_func_entry.feature (eif_access(pfe_import_func_entry.a_class), pbData, pvCallbackContext, ulLength);
	}
	return pfe_import_func_dummy_return_value;
}
void set_pfe_import_func_entry (void* a_class, void* a_feature)
{
	pfe_import_func_entry.a_class = eif_adopt(a_class);
	pfe_import_func_entry.feature = (pfe_import_func_eiffel_feature) a_feature;
}
void* get_pfe_import_func_stub ()
{
	return (void*) pfe_import_func_stub;
}
DWORD call_pfe_import_func (void* a_function, PBYTE pbData, PVOID pvCallbackContext, PULONG ulLength)
{
	return ((DWORD(*)(PBYTE pbData, PVOID pvCallbackContext, PULONG ulLength))a_function)(pbData, pvCallbackContext, ulLength);
}
struct lpoverlapped_completion_routine_entry_struct lpoverlapped_completion_routine_entry = {NULL, NULL};
void __stdcall lpoverlapped_completion_routine_stub (DWORD dwErrorCode, DWORD dwNumberOfBytesTransfered, LPOVERLAPPED lpOverlapped)
{
	if (lpoverlapped_completion_routine_entry.a_class != NULL && lpoverlapped_completion_routine_entry.feature != NULL)
	{
		lpoverlapped_completion_routine_entry.feature (eif_access(lpoverlapped_completion_routine_entry.a_class), dwErrorCode, dwNumberOfBytesTransfered, lpOverlapped);
	}
}
void set_lpoverlapped_completion_routine_entry (void* a_class, void* a_feature)
{
	lpoverlapped_completion_routine_entry.a_class = eif_adopt(a_class);
	lpoverlapped_completion_routine_entry.feature = (lpoverlapped_completion_routine_eiffel_feature) a_feature;
}
void* get_lpoverlapped_completion_routine_stub ()
{
	return (void*) lpoverlapped_completion_routine_stub;
}
void call_lpoverlapped_completion_routine (void* a_function, DWORD dwErrorCode, DWORD dwNumberOfBytesTransfered, LPOVERLAPPED lpOverlapped)
{
	((void(*)(DWORD dwErrorCode, DWORD dwNumberOfBytesTransfered, LPOVERLAPPED lpOverlapped))a_function)(dwErrorCode, dwNumberOfBytesTransfered, lpOverlapped);
}
struct enumrestypeproc_entry_struct enumrestypeproc_entry = {NULL, NULL};
BOOL enumrestypeproc_dummy_return_value;
BOOL __stdcall enumrestypeproc_stub (HMODULE hModule, LPTSTR lpType, LONG lParam)
{
	if (enumrestypeproc_entry.a_class != NULL && enumrestypeproc_entry.feature != NULL)
	{
		return enumrestypeproc_entry.feature (eif_access(enumrestypeproc_entry.a_class), hModule, lpType, lParam);
	}
	return enumrestypeproc_dummy_return_value;
}
void set_enumrestypeproc_entry (void* a_class, void* a_feature)
{
	enumrestypeproc_entry.a_class = eif_adopt(a_class);
	enumrestypeproc_entry.feature = (enumrestypeproc_eiffel_feature) a_feature;
}
void* get_enumrestypeproc_stub ()
{
	return (void*) enumrestypeproc_stub;
}
BOOL call_enumrestypeproc (void* a_function, HMODULE hModule, LPTSTR lpType, LONG lParam)
{
	return ((BOOL(*)(HMODULE hModule, LPTSTR lpType, LONG lParam))a_function)(hModule, lpType, lParam);
}
struct enumresnameproc_entry_struct enumresnameproc_entry = {NULL, NULL};
BOOL enumresnameproc_dummy_return_value;
BOOL __stdcall enumresnameproc_stub (HMODULE hModule, LPCTSTR lpType, LPTSTR lpName, LONG lParam)
{
	if (enumresnameproc_entry.a_class != NULL && enumresnameproc_entry.feature != NULL)
	{
		return enumresnameproc_entry.feature (eif_access(enumresnameproc_entry.a_class), hModule, lpType, lpName, lParam);
	}
	return enumresnameproc_dummy_return_value;
}
void set_enumresnameproc_entry (void* a_class, void* a_feature)
{
	enumresnameproc_entry.a_class = eif_adopt(a_class);
	enumresnameproc_entry.feature = (enumresnameproc_eiffel_feature) a_feature;
}
void* get_enumresnameproc_stub ()
{
	return (void*) enumresnameproc_stub;
}
BOOL call_enumresnameproc (void* a_function, HMODULE hModule, LPCTSTR lpType, LPTSTR lpName, LONG lParam)
{
	return ((BOOL(*)(HMODULE hModule, LPCTSTR lpType, LPTSTR lpName, LONG lParam))a_function)(hModule, lpType, lpName, lParam);
}
struct enumreslangproc_entry_struct enumreslangproc_entry = {NULL, NULL};
BOOL enumreslangproc_dummy_return_value;
BOOL __stdcall enumreslangproc_stub (HMODULE hModule, LPCTSTR lpType, LPCTSTR lpName, WORD wLanguage, LONG lParam)
{
	if (enumreslangproc_entry.a_class != NULL && enumreslangproc_entry.feature != NULL)
	{
		return enumreslangproc_entry.feature (eif_access(enumreslangproc_entry.a_class), hModule, lpType, lpName, wLanguage, lParam);
	}
	return enumreslangproc_dummy_return_value;
}
void set_enumreslangproc_entry (void* a_class, void* a_feature)
{
	enumreslangproc_entry.a_class = eif_adopt(a_class);
	enumreslangproc_entry.feature = (enumreslangproc_eiffel_feature) a_feature;
}
void* get_enumreslangproc_stub ()
{
	return (void*) enumreslangproc_stub;
}
BOOL call_enumreslangproc (void* a_function, HMODULE hModule, LPCTSTR lpType, LPCTSTR lpName, WORD wLanguage, LONG lParam)
{
	return ((BOOL(*)(HMODULE hModule, LPCTSTR lpType, LPCTSTR lpName, WORD wLanguage, LONG lParam))a_function)(hModule, lpType, lpName, wLanguage, lParam);
}
struct oldfontenumproca_entry_struct oldfontenumproca_entry = {NULL, NULL};
int oldfontenumproca_dummy_return_value;
int __stdcall oldfontenumproca_stub (LOGFONTA const * anonymous_1, TEXTMETRICA const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4)
{
	if (oldfontenumproca_entry.a_class != NULL && oldfontenumproca_entry.feature != NULL)
	{
		return oldfontenumproca_entry.feature (eif_access(oldfontenumproca_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return oldfontenumproca_dummy_return_value;
}
void set_oldfontenumproca_entry (void* a_class, void* a_feature)
{
	oldfontenumproca_entry.a_class = eif_adopt(a_class);
	oldfontenumproca_entry.feature = (oldfontenumproca_eiffel_feature) a_feature;
}
void* get_oldfontenumproca_stub ()
{
	return (void*) oldfontenumproca_stub;
}
int call_oldfontenumproca (void* a_function, LOGFONTA const * anonymous_1, TEXTMETRICA const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4)
{
	return ((int(*)(LOGFONTA const * anonymous_1, TEXTMETRICA const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct oldfontenumprocw_entry_struct oldfontenumprocw_entry = {NULL, NULL};
int oldfontenumprocw_dummy_return_value;
int __stdcall oldfontenumprocw_stub (LOGFONTW const * anonymous_1, TEXTMETRICW const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4)
{
	if (oldfontenumprocw_entry.a_class != NULL && oldfontenumprocw_entry.feature != NULL)
	{
		return oldfontenumprocw_entry.feature (eif_access(oldfontenumprocw_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return oldfontenumprocw_dummy_return_value;
}
void set_oldfontenumprocw_entry (void* a_class, void* a_feature)
{
	oldfontenumprocw_entry.a_class = eif_adopt(a_class);
	oldfontenumprocw_entry.feature = (oldfontenumprocw_eiffel_feature) a_feature;
}
void* get_oldfontenumprocw_stub ()
{
	return (void*) oldfontenumprocw_stub;
}
int call_oldfontenumprocw (void* a_function, LOGFONTW const * anonymous_1, TEXTMETRICW const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4)
{
	return ((int(*)(LOGFONTW const * anonymous_1, TEXTMETRICW const * anonymous_2, DWORD anonymous_3, LPARAM anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct gobjenumproc_entry_struct gobjenumproc_entry = {NULL, NULL};
int gobjenumproc_dummy_return_value;
int __stdcall gobjenumproc_stub (LPVOID anonymous_1, LPARAM anonymous_2)
{
	if (gobjenumproc_entry.a_class != NULL && gobjenumproc_entry.feature != NULL)
	{
		return gobjenumproc_entry.feature (eif_access(gobjenumproc_entry.a_class), anonymous_1, anonymous_2);
	}
	return gobjenumproc_dummy_return_value;
}
void set_gobjenumproc_entry (void* a_class, void* a_feature)
{
	gobjenumproc_entry.a_class = eif_adopt(a_class);
	gobjenumproc_entry.feature = (gobjenumproc_eiffel_feature) a_feature;
}
void* get_gobjenumproc_stub ()
{
	return (void*) gobjenumproc_stub;
}
int call_gobjenumproc (void* a_function, LPVOID anonymous_1, LPARAM anonymous_2)
{
	return ((int(*)(LPVOID anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct lineddaproc_entry_struct lineddaproc_entry = {NULL, NULL};
void __stdcall lineddaproc_stub (int anonymous_1, int anonymous_2, LPARAM anonymous_3)
{
	if (lineddaproc_entry.a_class != NULL && lineddaproc_entry.feature != NULL)
	{
		lineddaproc_entry.feature (eif_access(lineddaproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3);
	}
}
void set_lineddaproc_entry (void* a_class, void* a_feature)
{
	lineddaproc_entry.a_class = eif_adopt(a_class);
	lineddaproc_entry.feature = (lineddaproc_eiffel_feature) a_feature;
}
void* get_lineddaproc_stub ()
{
	return (void*) lineddaproc_stub;
}
void call_lineddaproc (void* a_function, int anonymous_1, int anonymous_2, LPARAM anonymous_3)
{
	((void(*)(int anonymous_1, int anonymous_2, LPARAM anonymous_3))a_function)(anonymous_1, anonymous_2, anonymous_3);
}
struct lpfndevmode_entry_struct lpfndevmode_entry = {NULL, NULL};
UINT lpfndevmode_dummy_return_value;
UINT __stdcall lpfndevmode_stub (HWND anonymous_1, HMODULE anonymous_2, LPDEVMODE anonymous_3, LPSTR anonymous_4, LPSTR anonymous_5, LPDEVMODE anonymous_6, LPSTR anonymous_7, UINT anonymous_8)
{
	if (lpfndevmode_entry.a_class != NULL && lpfndevmode_entry.feature != NULL)
	{
		return lpfndevmode_entry.feature (eif_access(lpfndevmode_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5, anonymous_6, anonymous_7, anonymous_8);
	}
	return lpfndevmode_dummy_return_value;
}
void set_lpfndevmode_entry (void* a_class, void* a_feature)
{
	lpfndevmode_entry.a_class = eif_adopt(a_class);
	lpfndevmode_entry.feature = (lpfndevmode_eiffel_feature) a_feature;
}
void* get_lpfndevmode_stub ()
{
	return (void*) lpfndevmode_stub;
}
UINT call_lpfndevmode (void* a_function, HWND anonymous_1, HMODULE anonymous_2, LPDEVMODE anonymous_3, LPSTR anonymous_4, LPSTR anonymous_5, LPDEVMODE anonymous_6, LPSTR anonymous_7, UINT anonymous_8)
{
	return ((UINT(*)(HWND anonymous_1, HMODULE anonymous_2, LPDEVMODE anonymous_3, LPSTR anonymous_4, LPSTR anonymous_5, LPDEVMODE anonymous_6, LPSTR anonymous_7, UINT anonymous_8))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5, anonymous_6, anonymous_7, anonymous_8);
}
struct lpfndevcaps_entry_struct lpfndevcaps_entry = {NULL, NULL};
DWORD lpfndevcaps_dummy_return_value;
DWORD __stdcall lpfndevcaps_stub (LPSTR anonymous_1, LPSTR anonymous_2, UINT anonymous_3, LPSTR anonymous_4, LPDEVMODE anonymous_5)
{
	if (lpfndevcaps_entry.a_class != NULL && lpfndevcaps_entry.feature != NULL)
	{
		return lpfndevcaps_entry.feature (eif_access(lpfndevcaps_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
	}
	return lpfndevcaps_dummy_return_value;
}
void set_lpfndevcaps_entry (void* a_class, void* a_feature)
{
	lpfndevcaps_entry.a_class = eif_adopt(a_class);
	lpfndevcaps_entry.feature = (lpfndevcaps_eiffel_feature) a_feature;
}
void* get_lpfndevcaps_stub ()
{
	return (void*) lpfndevcaps_stub;
}
DWORD call_lpfndevcaps (void* a_function, LPSTR anonymous_1, LPSTR anonymous_2, UINT anonymous_3, LPSTR anonymous_4, LPDEVMODE anonymous_5)
{
	return ((DWORD(*)(LPSTR anonymous_1, LPSTR anonymous_2, UINT anonymous_3, LPSTR anonymous_4, LPDEVMODE anonymous_5))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
}
struct mfenumproc_entry_struct mfenumproc_entry = {NULL, NULL};
int mfenumproc_dummy_return_value;
int __stdcall mfenumproc_stub (HDC anonymous_1, HANDLETABLE * anonymous_2, METARECORD * anonymous_3, int anonymous_4, LPARAM anonymous_5)
{
	if (mfenumproc_entry.a_class != NULL && mfenumproc_entry.feature != NULL)
	{
		return mfenumproc_entry.feature (eif_access(mfenumproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
	}
	return mfenumproc_dummy_return_value;
}
void set_mfenumproc_entry (void* a_class, void* a_feature)
{
	mfenumproc_entry.a_class = eif_adopt(a_class);
	mfenumproc_entry.feature = (mfenumproc_eiffel_feature) a_feature;
}
void* get_mfenumproc_stub ()
{
	return (void*) mfenumproc_stub;
}
int call_mfenumproc (void* a_function, HDC anonymous_1, HANDLETABLE * anonymous_2, METARECORD * anonymous_3, int anonymous_4, LPARAM anonymous_5)
{
	return ((int(*)(HDC anonymous_1, HANDLETABLE * anonymous_2, METARECORD * anonymous_3, int anonymous_4, LPARAM anonymous_5))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
}
struct enhmfenumproc_entry_struct enhmfenumproc_entry = {NULL, NULL};
int enhmfenumproc_dummy_return_value;
int __stdcall enhmfenumproc_stub (HDC anonymous_1, HANDLETABLE * anonymous_2, ENHMETARECORD const * anonymous_3, int anonymous_4, LPARAM anonymous_5)
{
	if (enhmfenumproc_entry.a_class != NULL && enhmfenumproc_entry.feature != NULL)
	{
		return enhmfenumproc_entry.feature (eif_access(enhmfenumproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
	}
	return enhmfenumproc_dummy_return_value;
}
void set_enhmfenumproc_entry (void* a_class, void* a_feature)
{
	enhmfenumproc_entry.a_class = eif_adopt(a_class);
	enhmfenumproc_entry.feature = (enhmfenumproc_eiffel_feature) a_feature;
}
void* get_enhmfenumproc_stub ()
{
	return (void*) enhmfenumproc_stub;
}
int call_enhmfenumproc (void* a_function, HDC anonymous_1, HANDLETABLE * anonymous_2, ENHMETARECORD const * anonymous_3, int anonymous_4, LPARAM anonymous_5)
{
	return ((int(*)(HDC anonymous_1, HANDLETABLE * anonymous_2, ENHMETARECORD const * anonymous_3, int anonymous_4, LPARAM anonymous_5))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4, anonymous_5);
}
struct abortproc_entry_struct abortproc_entry = {NULL, NULL};
BOOL abortproc_dummy_return_value;
BOOL __stdcall abortproc_stub (HDC anonymous_1, int anonymous_2)
{
	if (abortproc_entry.a_class != NULL && abortproc_entry.feature != NULL)
	{
		return abortproc_entry.feature (eif_access(abortproc_entry.a_class), anonymous_1, anonymous_2);
	}
	return abortproc_dummy_return_value;
}
void set_abortproc_entry (void* a_class, void* a_feature)
{
	abortproc_entry.a_class = eif_adopt(a_class);
	abortproc_entry.feature = (abortproc_eiffel_feature) a_feature;
}
void* get_abortproc_stub ()
{
	return (void*) abortproc_stub;
}
BOOL call_abortproc (void* a_function, HDC anonymous_1, int anonymous_2)
{
	return ((BOOL(*)(HDC anonymous_1, int anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct icmenumproca_entry_struct icmenumproca_entry = {NULL, NULL};
int icmenumproca_dummy_return_value;
int __stdcall icmenumproca_stub (LPSTR anonymous_1, LPARAM anonymous_2)
{
	if (icmenumproca_entry.a_class != NULL && icmenumproca_entry.feature != NULL)
	{
		return icmenumproca_entry.feature (eif_access(icmenumproca_entry.a_class), anonymous_1, anonymous_2);
	}
	return icmenumproca_dummy_return_value;
}
void set_icmenumproca_entry (void* a_class, void* a_feature)
{
	icmenumproca_entry.a_class = eif_adopt(a_class);
	icmenumproca_entry.feature = (icmenumproca_eiffel_feature) a_feature;
}
void* get_icmenumproca_stub ()
{
	return (void*) icmenumproca_stub;
}
int call_icmenumproca (void* a_function, LPSTR anonymous_1, LPARAM anonymous_2)
{
	return ((int(*)(LPSTR anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct icmenumprocw_entry_struct icmenumprocw_entry = {NULL, NULL};
int icmenumprocw_dummy_return_value;
int __stdcall icmenumprocw_stub (LPWSTR anonymous_1, LPARAM anonymous_2)
{
	if (icmenumprocw_entry.a_class != NULL && icmenumprocw_entry.feature != NULL)
	{
		return icmenumprocw_entry.feature (eif_access(icmenumprocw_entry.a_class), anonymous_1, anonymous_2);
	}
	return icmenumprocw_dummy_return_value;
}
void set_icmenumprocw_entry (void* a_class, void* a_feature)
{
	icmenumprocw_entry.a_class = eif_adopt(a_class);
	icmenumprocw_entry.feature = (icmenumprocw_eiffel_feature) a_feature;
}
void* get_icmenumprocw_stub ()
{
	return (void*) icmenumprocw_stub;
}
int call_icmenumprocw (void* a_function, LPWSTR anonymous_1, LPARAM anonymous_2)
{
	return ((int(*)(LPWSTR anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct wndproc_entry_struct wndproc_entry = {NULL, NULL};
LRESULT wndproc_dummy_return_value;
LRESULT __stdcall wndproc_stub (HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4)
{
	if (wndproc_entry.a_class != NULL && wndproc_entry.feature != NULL)
	{
		return wndproc_entry.feature (eif_access(wndproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return wndproc_dummy_return_value;
}
void set_wndproc_entry (void* a_class, void* a_feature)
{
	wndproc_entry.a_class = eif_adopt(a_class);
	wndproc_entry.feature = (wndproc_eiffel_feature) a_feature;
}
void* get_wndproc_stub ()
{
	return (void*) wndproc_stub;
}
LRESULT call_wndproc (void* a_function, HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4)
{
	return ((LRESULT(*)(HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct dlgproc_entry_struct dlgproc_entry = {NULL, NULL};
BOOL dlgproc_dummy_return_value;
BOOL __stdcall dlgproc_stub (HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4)
{
	if (dlgproc_entry.a_class != NULL && dlgproc_entry.feature != NULL)
	{
		return dlgproc_entry.feature (eif_access(dlgproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return dlgproc_dummy_return_value;
}
void set_dlgproc_entry (void* a_class, void* a_feature)
{
	dlgproc_entry.a_class = eif_adopt(a_class);
	dlgproc_entry.feature = (dlgproc_eiffel_feature) a_feature;
}
void* get_dlgproc_stub ()
{
	return (void*) dlgproc_stub;
}
BOOL call_dlgproc (void* a_function, HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4)
{
	return ((BOOL(*)(HWND anonymous_1, UINT anonymous_2, WPARAM anonymous_3, LPARAM anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct timerproc_entry_struct timerproc_entry = {NULL, NULL};
void __stdcall timerproc_stub (HWND anonymous_1, UINT anonymous_2, UINT anonymous_3, DWORD anonymous_4)
{
	if (timerproc_entry.a_class != NULL && timerproc_entry.feature != NULL)
	{
		timerproc_entry.feature (eif_access(timerproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
}
void set_timerproc_entry (void* a_class, void* a_feature)
{
	timerproc_entry.a_class = eif_adopt(a_class);
	timerproc_entry.feature = (timerproc_eiffel_feature) a_feature;
}
void* get_timerproc_stub ()
{
	return (void*) timerproc_stub;
}
void call_timerproc (void* a_function, HWND anonymous_1, UINT anonymous_2, UINT anonymous_3, DWORD anonymous_4)
{
	((void(*)(HWND anonymous_1, UINT anonymous_2, UINT anonymous_3, DWORD anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct graystringproc_entry_struct graystringproc_entry = {NULL, NULL};
BOOL graystringproc_dummy_return_value;
BOOL __stdcall graystringproc_stub (HDC anonymous_1, LPARAM anonymous_2, int anonymous_3)
{
	if (graystringproc_entry.a_class != NULL && graystringproc_entry.feature != NULL)
	{
		return graystringproc_entry.feature (eif_access(graystringproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3);
	}
	return graystringproc_dummy_return_value;
}
void set_graystringproc_entry (void* a_class, void* a_feature)
{
	graystringproc_entry.a_class = eif_adopt(a_class);
	graystringproc_entry.feature = (graystringproc_eiffel_feature) a_feature;
}
void* get_graystringproc_stub ()
{
	return (void*) graystringproc_stub;
}
BOOL call_graystringproc (void* a_function, HDC anonymous_1, LPARAM anonymous_2, int anonymous_3)
{
	return ((BOOL(*)(HDC anonymous_1, LPARAM anonymous_2, int anonymous_3))a_function)(anonymous_1, anonymous_2, anonymous_3);
}
struct wndenumproc_entry_struct wndenumproc_entry = {NULL, NULL};
BOOL wndenumproc_dummy_return_value;
BOOL __stdcall wndenumproc_stub (HWND anonymous_1, LPARAM anonymous_2)
{
	if (wndenumproc_entry.a_class != NULL && wndenumproc_entry.feature != NULL)
	{
		return wndenumproc_entry.feature (eif_access(wndenumproc_entry.a_class), anonymous_1, anonymous_2);
	}
	return wndenumproc_dummy_return_value;
}
void set_wndenumproc_entry (void* a_class, void* a_feature)
{
	wndenumproc_entry.a_class = eif_adopt(a_class);
	wndenumproc_entry.feature = (wndenumproc_eiffel_feature) a_feature;
}
void* get_wndenumproc_stub ()
{
	return (void*) wndenumproc_stub;
}
BOOL call_wndenumproc (void* a_function, HWND anonymous_1, LPARAM anonymous_2)
{
	return ((BOOL(*)(HWND anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct hookproc_entry_struct hookproc_entry = {NULL, NULL};
LRESULT hookproc_dummy_return_value;
LRESULT __stdcall hookproc_stub (int code, WPARAM wParam, LPARAM lParam)
{
	if (hookproc_entry.a_class != NULL && hookproc_entry.feature != NULL)
	{
		return hookproc_entry.feature (eif_access(hookproc_entry.a_class), code, wParam, lParam);
	}
	return hookproc_dummy_return_value;
}
void set_hookproc_entry (void* a_class, void* a_feature)
{
	hookproc_entry.a_class = eif_adopt(a_class);
	hookproc_entry.feature = (hookproc_eiffel_feature) a_feature;
}
void* get_hookproc_stub ()
{
	return (void*) hookproc_stub;
}
LRESULT call_hookproc (void* a_function, int code, WPARAM wParam, LPARAM lParam)
{
	return ((LRESULT(*)(int code, WPARAM wParam, LPARAM lParam))a_function)(code, wParam, lParam);
}
struct sendasyncproc_entry_struct sendasyncproc_entry = {NULL, NULL};
void __stdcall sendasyncproc_stub (HWND anonymous_1, UINT anonymous_2, DWORD anonymous_3, LRESULT anonymous_4)
{
	if (sendasyncproc_entry.a_class != NULL && sendasyncproc_entry.feature != NULL)
	{
		sendasyncproc_entry.feature (eif_access(sendasyncproc_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
}
void set_sendasyncproc_entry (void* a_class, void* a_feature)
{
	sendasyncproc_entry.a_class = eif_adopt(a_class);
	sendasyncproc_entry.feature = (sendasyncproc_eiffel_feature) a_feature;
}
void* get_sendasyncproc_stub ()
{
	return (void*) sendasyncproc_stub;
}
void call_sendasyncproc (void* a_function, HWND anonymous_1, UINT anonymous_2, DWORD anonymous_3, LRESULT anonymous_4)
{
	((void(*)(HWND anonymous_1, UINT anonymous_2, DWORD anonymous_3, LRESULT anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct propenumproca_entry_struct propenumproca_entry = {NULL, NULL};
BOOL propenumproca_dummy_return_value;
BOOL __stdcall propenumproca_stub (HWND anonymous_1, LPCSTR anonymous_2, HANDLE anonymous_3)
{
	if (propenumproca_entry.a_class != NULL && propenumproca_entry.feature != NULL)
	{
		return propenumproca_entry.feature (eif_access(propenumproca_entry.a_class), anonymous_1, anonymous_2, anonymous_3);
	}
	return propenumproca_dummy_return_value;
}
void set_propenumproca_entry (void* a_class, void* a_feature)
{
	propenumproca_entry.a_class = eif_adopt(a_class);
	propenumproca_entry.feature = (propenumproca_eiffel_feature) a_feature;
}
void* get_propenumproca_stub ()
{
	return (void*) propenumproca_stub;
}
BOOL call_propenumproca (void* a_function, HWND anonymous_1, LPCSTR anonymous_2, HANDLE anonymous_3)
{
	return ((BOOL(*)(HWND anonymous_1, LPCSTR anonymous_2, HANDLE anonymous_3))a_function)(anonymous_1, anonymous_2, anonymous_3);
}
struct propenumprocw_entry_struct propenumprocw_entry = {NULL, NULL};
BOOL propenumprocw_dummy_return_value;
BOOL __stdcall propenumprocw_stub (HWND anonymous_1, LPCWSTR anonymous_2, HANDLE anonymous_3)
{
	if (propenumprocw_entry.a_class != NULL && propenumprocw_entry.feature != NULL)
	{
		return propenumprocw_entry.feature (eif_access(propenumprocw_entry.a_class), anonymous_1, anonymous_2, anonymous_3);
	}
	return propenumprocw_dummy_return_value;
}
void set_propenumprocw_entry (void* a_class, void* a_feature)
{
	propenumprocw_entry.a_class = eif_adopt(a_class);
	propenumprocw_entry.feature = (propenumprocw_eiffel_feature) a_feature;
}
void* get_propenumprocw_stub ()
{
	return (void*) propenumprocw_stub;
}
BOOL call_propenumprocw (void* a_function, HWND anonymous_1, LPCWSTR anonymous_2, HANDLE anonymous_3)
{
	return ((BOOL(*)(HWND anonymous_1, LPCWSTR anonymous_2, HANDLE anonymous_3))a_function)(anonymous_1, anonymous_2, anonymous_3);
}
struct propenumprocexa_entry_struct propenumprocexa_entry = {NULL, NULL};
BOOL propenumprocexa_dummy_return_value;
BOOL __stdcall propenumprocexa_stub (HWND anonymous_1, LPSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4)
{
	if (propenumprocexa_entry.a_class != NULL && propenumprocexa_entry.feature != NULL)
	{
		return propenumprocexa_entry.feature (eif_access(propenumprocexa_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return propenumprocexa_dummy_return_value;
}
void set_propenumprocexa_entry (void* a_class, void* a_feature)
{
	propenumprocexa_entry.a_class = eif_adopt(a_class);
	propenumprocexa_entry.feature = (propenumprocexa_eiffel_feature) a_feature;
}
void* get_propenumprocexa_stub ()
{
	return (void*) propenumprocexa_stub;
}
BOOL call_propenumprocexa (void* a_function, HWND anonymous_1, LPSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4)
{
	return ((BOOL(*)(HWND anonymous_1, LPSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct propenumprocexw_entry_struct propenumprocexw_entry = {NULL, NULL};
BOOL propenumprocexw_dummy_return_value;
BOOL __stdcall propenumprocexw_stub (HWND anonymous_1, LPWSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4)
{
	if (propenumprocexw_entry.a_class != NULL && propenumprocexw_entry.feature != NULL)
	{
		return propenumprocexw_entry.feature (eif_access(propenumprocexw_entry.a_class), anonymous_1, anonymous_2, anonymous_3, anonymous_4);
	}
	return propenumprocexw_dummy_return_value;
}
void set_propenumprocexw_entry (void* a_class, void* a_feature)
{
	propenumprocexw_entry.a_class = eif_adopt(a_class);
	propenumprocexw_entry.feature = (propenumprocexw_eiffel_feature) a_feature;
}
void* get_propenumprocexw_stub ()
{
	return (void*) propenumprocexw_stub;
}
BOOL call_propenumprocexw (void* a_function, HWND anonymous_1, LPWSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4)
{
	return ((BOOL(*)(HWND anonymous_1, LPWSTR anonymous_2, HANDLE anonymous_3, DWORD anonymous_4))a_function)(anonymous_1, anonymous_2, anonymous_3, anonymous_4);
}
struct editwordbreakproca_entry_struct editwordbreakproca_entry = {NULL, NULL};
int editwordbreakproca_dummy_return_value;
int __stdcall editwordbreakproca_stub (LPSTR lpch, int ichCurrent, int cch, int code)
{
	if (editwordbreakproca_entry.a_class != NULL && editwordbreakproca_entry.feature != NULL)
	{
		return editwordbreakproca_entry.feature (eif_access(editwordbreakproca_entry.a_class), lpch, ichCurrent, cch, code);
	}
	return editwordbreakproca_dummy_return_value;
}
void set_editwordbreakproca_entry (void* a_class, void* a_feature)
{
	editwordbreakproca_entry.a_class = eif_adopt(a_class);
	editwordbreakproca_entry.feature = (editwordbreakproca_eiffel_feature) a_feature;
}
void* get_editwordbreakproca_stub ()
{
	return (void*) editwordbreakproca_stub;
}
int call_editwordbreakproca (void* a_function, LPSTR lpch, int ichCurrent, int cch, int code)
{
	return ((int(*)(LPSTR lpch, int ichCurrent, int cch, int code))a_function)(lpch, ichCurrent, cch, code);
}
struct editwordbreakprocw_entry_struct editwordbreakprocw_entry = {NULL, NULL};
int editwordbreakprocw_dummy_return_value;
int __stdcall editwordbreakprocw_stub (LPWSTR lpch, int ichCurrent, int cch, int code)
{
	if (editwordbreakprocw_entry.a_class != NULL && editwordbreakprocw_entry.feature != NULL)
	{
		return editwordbreakprocw_entry.feature (eif_access(editwordbreakprocw_entry.a_class), lpch, ichCurrent, cch, code);
	}
	return editwordbreakprocw_dummy_return_value;
}
void set_editwordbreakprocw_entry (void* a_class, void* a_feature)
{
	editwordbreakprocw_entry.a_class = eif_adopt(a_class);
	editwordbreakprocw_entry.feature = (editwordbreakprocw_eiffel_feature) a_feature;
}
void* get_editwordbreakprocw_stub ()
{
	return (void*) editwordbreakprocw_stub;
}
int call_editwordbreakprocw (void* a_function, LPWSTR lpch, int ichCurrent, int cch, int code)
{
	return ((int(*)(LPWSTR lpch, int ichCurrent, int cch, int code))a_function)(lpch, ichCurrent, cch, code);
}
struct drawstateproc_entry_struct drawstateproc_entry = {NULL, NULL};
BOOL drawstateproc_dummy_return_value;
BOOL __stdcall drawstateproc_stub (HDC hdc, LPARAM lData, WPARAM wData, int cx, int cy)
{
	if (drawstateproc_entry.a_class != NULL && drawstateproc_entry.feature != NULL)
	{
		return drawstateproc_entry.feature (eif_access(drawstateproc_entry.a_class), hdc, lData, wData, cx, cy);
	}
	return drawstateproc_dummy_return_value;
}
void set_drawstateproc_entry (void* a_class, void* a_feature)
{
	drawstateproc_entry.a_class = eif_adopt(a_class);
	drawstateproc_entry.feature = (drawstateproc_eiffel_feature) a_feature;
}
void* get_drawstateproc_stub ()
{
	return (void*) drawstateproc_stub;
}
BOOL call_drawstateproc (void* a_function, HDC hdc, LPARAM lData, WPARAM wData, int cx, int cy)
{
	return ((BOOL(*)(HDC hdc, LPARAM lData, WPARAM wData, int cx, int cy))a_function)(hdc, lData, wData, cx, cy);
}
struct nameenumproca_entry_struct nameenumproca_entry = {NULL, NULL};
BOOL nameenumproca_dummy_return_value;
BOOL __stdcall nameenumproca_stub (LPSTR anonymous_1, LPARAM anonymous_2)
{
	if (nameenumproca_entry.a_class != NULL && nameenumproca_entry.feature != NULL)
	{
		return nameenumproca_entry.feature (eif_access(nameenumproca_entry.a_class), anonymous_1, anonymous_2);
	}
	return nameenumproca_dummy_return_value;
}
void set_nameenumproca_entry (void* a_class, void* a_feature)
{
	nameenumproca_entry.a_class = eif_adopt(a_class);
	nameenumproca_entry.feature = (nameenumproca_eiffel_feature) a_feature;
}
void* get_nameenumproca_stub ()
{
	return (void*) nameenumproca_stub;
}
BOOL call_nameenumproca (void* a_function, LPSTR anonymous_1, LPARAM anonymous_2)
{
	return ((BOOL(*)(LPSTR anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct nameenumprocw_entry_struct nameenumprocw_entry = {NULL, NULL};
BOOL nameenumprocw_dummy_return_value;
BOOL __stdcall nameenumprocw_stub (LPWSTR anonymous_1, LPARAM anonymous_2)
{
	if (nameenumprocw_entry.a_class != NULL && nameenumprocw_entry.feature != NULL)
	{
		return nameenumprocw_entry.feature (eif_access(nameenumprocw_entry.a_class), anonymous_1, anonymous_2);
	}
	return nameenumprocw_dummy_return_value;
}
void set_nameenumprocw_entry (void* a_class, void* a_feature)
{
	nameenumprocw_entry.a_class = eif_adopt(a_class);
	nameenumprocw_entry.feature = (nameenumprocw_eiffel_feature) a_feature;
}
void* get_nameenumprocw_stub ()
{
	return (void*) nameenumprocw_stub;
}
BOOL call_nameenumprocw (void* a_function, LPWSTR anonymous_1, LPARAM anonymous_2)
{
	return ((BOOL(*)(LPWSTR anonymous_1, LPARAM anonymous_2))a_function)(anonymous_1, anonymous_2);
}
struct msgboxcallback_entry_struct msgboxcallback_entry = {NULL, NULL};
void __stdcall msgboxcallback_stub (LPHELPINFO lpHelpInfo)
{
	if (msgboxcallback_entry.a_class != NULL && msgboxcallback_entry.feature != NULL)
	{
		msgboxcallback_entry.feature (eif_access(msgboxcallback_entry.a_class), lpHelpInfo);
	}
}
void set_msgboxcallback_entry (void* a_class, void* a_feature)
{
	msgboxcallback_entry.a_class = eif_adopt(a_class);
	msgboxcallback_entry.feature = (msgboxcallback_eiffel_feature) a_feature;
}
void* get_msgboxcallback_stub ()
{
	return (void*) msgboxcallback_stub;
}
void call_msgboxcallback (void* a_function, LPHELPINFO lpHelpInfo)
{
	((void(*)(LPHELPINFO lpHelpInfo))a_function)(lpHelpInfo);
}

